### ISSUE TITLE
Wifi configuration not working

### ISSUE THREAD

**Issue by Fgonzalez22** [SensESP/SensESP-project-template#3]
When trying to connect to sensesp with mobile to configure as client to existing wifi, the scan is done correctly, the network can be selected and its name appears in the window, the password is entered manually or if no password is required is left blank. But the save button does not respond, nor the terminal in Platformio show any activity. In contrast when SK configuration is saved change and activity show in both the app and terminal.

**Comment by mairas** [comment]
You probably found out already, but there was a bug in SensESP 3.0.0-beta.1 frontend code that made it ignore the "Save" button press. It's fixed now and 3.0.0-beta.2 has been released.

**Comment by Fgonzalez22** [comment]
thanks, working fine now!

**Comment by mairas** [comment]
Excellent, thank you for the confirmation!
